# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'converter_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(544, 195)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.Convert_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Convert_btn.setGeometry(QtCore.QRect(410, 120, 121, 23))
        self.Convert_btn.setObjectName("Convert_btn")
        self.SFM_Folder = QtWidgets.QLineEdit(self.centralwidget)
        self.SFM_Folder.setGeometry(QtCore.QRect(20, 30, 381, 20))
        self.SFM_Folder.setObjectName("SFM_Folder")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 151, 16))
        self.label.setObjectName("label")
        self.REDxEYE = QtWidgets.QLabel(self.centralwidget)
        self.REDxEYE.setGeometry(QtCore.QRect(20, 110, 181, 16))
        self.REDxEYE.setObjectName("REDxEYE")
        self.Firend_Endlire = QtWidgets.QLabel(self.centralwidget)
        self.Firend_Endlire.setGeometry(QtCore.QRect(20, 130, 191, 16))
        self.Firend_Endlire.setObjectName("Firend_Endlire")
        self.S2FM_Folder = QtWidgets.QLineEdit(self.centralwidget)
        self.S2FM_Folder.setGeometry(QtCore.QRect(20, 80, 381, 20))
        self.S2FM_Folder.setObjectName("S2FM_Folder")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 151, 16))
        self.label_2.setObjectName("label_2")
        self.Save_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Save_btn.setGeometry(QtCore.QRect(410, 80, 121, 23))
        self.Save_btn.setObjectName("Save_btn")
        self.check_compile = QtWidgets.QCheckBox(self.centralwidget)
        self.check_compile.setGeometry(QtCore.QRect(420, 30, 31, 17))
        self.check_compile.setObjectName("check_compile")
        self.check_sandbox = QtWidgets.QCheckBox(self.centralwidget)
        self.check_sandbox.setGeometry(QtCore.QRect(460, 30, 31, 17))
        self.check_sandbox.setObjectName("check_sandbox")
        self.check_debug = QtWidgets.QCheckBox(self.centralwidget)
        self.check_debug.setGeometry(QtCore.QRect(500, 30, 31, 17))
        self.check_debug.setObjectName("check_debug")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 544, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SFM to S2FM Model Porter"))
        self.Convert_btn.setText(_translate("MainWindow", "Convert"))
        self.label.setText(_translate("MainWindow", "SFM model folder:"))
        self.REDxEYE.setText(_translate("MainWindow", "Original converter made by REDxEYE"))
        self.Firend_Endlire.setText(_translate("MainWindow", "GUI made by Firend_Endlire"))
        self.label_2.setText(_translate("MainWindow", "S2FM model folder:"))
        self.Save_btn.setText(_translate("MainWindow", "Save path"))
        self.check_compile.setText(_translate("MainWindow", "-c"))
        self.check_sandbox.setText(_translate("MainWindow", "-s"))
        self.check_debug.setText(_translate("MainWindow", "-d"))
